### ISSUE TITLE
Plan of this package?

### ISSUE THREAD

**Issue by xukai92** [ekinakyurek/KnetLayers.jl#9]
Hi, what's the current plan of this package? Is this still active developed and maintained?

**Comment by ekinakyurek** [comment]
It is still active and I am on the v0.2.0 branch. 
I couldn't decide which API should use for RNN hidden states, and I'm looking for supporting Flux backend too.

Best,
Ekin

**Comment by xukai92** [comment]
Sounds great. I would be interested in merging some of my own codes for layers (https://github.com/xukai92/MLToolkit.jl/tree/master/src/neural) into this package, in which stochastic layers seem not supported here yet. I think they are very useful building blocks for probabilistic neural networks (e.g. VAEs). Do you have any plan on supporting them?

**Comment by ekinakyurek** [comment]
Hi that would be great! if you open a PR, I can check it out. You may want to add a test case or example, so that I can understand that they are working.

Best,
Ekin

**Comment by xukai92** [comment]
I switched to Flux.jl 3 months ago as I found it more Julia. That is to say I will probably not work on making any Knet layers any more.
